# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-15 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190713_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='delivery_locations',
            field=models.CharField(default='none', max_length=150),
        ),
    ]
