# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-09-13 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190715_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ref_number',
            field=models.CharField(default='no ref_number', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(default='08033334444', max_length=20),
        ),
    ]
