# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-05-12 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='img',
        ),
        migrations.AddField(
            model_name='meal',
            name='img_url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
